services:
  blog-app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - mongo_disk:/data/db

  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - 6379:6379

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-db
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-db
    ports:
      - 9092:9092

volumes:
  mongo_disk:
