apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mini-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage-pv
              mountPath: /data/db
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: mongo-storage-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
