apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-blog
  namespace: mini-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-blog
  template:
    metadata:
      labels:
        app: mini-blog
    spec:
      containers:
        - name: mini-blog
          image: aabv21/node-app-kubernetes:v1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mini-blog-config
            - secretRef:
                name: mini-blog-secret
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
